language: node_js
sudo: false
node_js:
  - "5"
deploy:
  provider: npm
  email: sandbox_JSUI@coveo.com
  skip_cleanup: true
  api_key:
    secure: kUnDz2fnWLYfw9vYhnC4Ha52Mg5LSpa2GS9BYu6O3hOHqREycLHEDaojbhLuCCTKGoPfAr2PSv7/weFFEaInQY5ZKnfAllzM0jUjYxNpoOYJJwSlbZCdOs0N+4MDd6U7FYOKmgqJTBb5YqedwrR7QjtZnwLgzpZaY8ZFTIyahOkI56WlvxZlQ2018nC2vClN80gtpY0y7Gh2TKvhh+6FVLHUjfBtyvMV5G5YBfa5Xn5kYcHumH3CgucA39ir3fjq7vT5TLLFzPmkqXcCnLV/JTHWZXCMSuvp6vwGfr9Fcm2tiEG/Xjl+7/zNvIxuPVzcKMbKzJVuDHzR3/z4a0KAx+Syb3YwURpgbt2inWuk0YoyCRSt+jxnC46dNOZmTg6bb29ohrT7KypRtfoj8w5wPuHH53zteY4OH5iG9GCy/EPxfRFAVz0Hcs07zR2vi4LMDh2aL9q4ss5I0SWBFaVkx17u0dogshV9ypXsGJMtNoZAXGarIiUJrJIeKYM6D8mjGXbpikuyEP8QhS+Ve4ehzaekD9PhhoXJIY+yaLzLRxXfnk6AJYIsnX73vBrNxwe+6KdF8n7Y/9F/iNwXmT7neJxAgeuxYn+eG0UnL25rBBg4NhqilNjweva+wUea0xcm4eR/LwmUhVr5HkbT/db6gzHmwg6N73t2JoTgWrrTROg=
  on:
    tags: true
    repo: coveo/sfdx-prebuilt
    all_branches: true