language: node_js
sudo: required
node_js:
  - "6"
deploy:
  provider: npm
  email: sandbox_JSUI@coveo.com
  skip_cleanup: true
  api_key:
    secure: "LCNVSNmgIhMeJfTnLl+1sqDPjN0Ge64UC0p1nCZJcGZtfLDTl9qrBuemCvjOIboWUwjE/dQiqyXecLErSbO4C+kaIjRYNsqrUicGK1AGkA4n9HNlbkJVCZ/FQtua1SycRZFRV/lGy+7gS9I3yV4S5TzjZOoXxnjOMQNzGPZHkaUQNQeL04qrRNQdMOkVaJ5fMxJBK3p7AJGDdixcsUpqDwMJfYS1suoKxC9SALHW/u7S/aW1O7th4JgKhj31CZbDZ3h2LSfetzltPu+MFSX7fsOamfjk2t4Yhpb/OvLAUM2hHpn/vAbJpMQUWjuSF9urp0AcxI8BLig9BrhnD04mDJ/5f1n7nybWJe9ZtwpewxqWPb0dakUTJo47OdDZ68Dpq+h5Dgz+34CGEKqKpAfzOnwTSYNYMtKo4uOjUDMtIHhM7wMHWzzLljszyGyOySizl/jiyjeqHsnYpjfdsJQHlG4U52aaG4qhF5U8PDP/cR687XaBP4+ETWTRMxgT1sgNX8U1+Ns7DEXRTUsnvpS2+qHkb4jid1tWpdL8weHv7KoHvEIe0I6DQHXz577JcDJvp27VXTqE1hQtwPzti0z0Ri4DagpmxB/NXHKhWt0XYUjOl/Eqi6z0LjX2wl/EdxsRnCKbGGkve86rnQW9Mphlpdk9aZ+6FEwBUwuHDmDfuDY="
  on:
    tags: true
    repo: coveo/sfdx-prebuilt
    all_branches: true